name: Deploy to VPS via Tailscale

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connect Tailscal
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Set up .env file on server
        run: |
          ssh -o "StrictHostKeyChecking no" github@server "
            cd /srv/cicdts
            git pull
            touch /srv/cicdts/backend/.env
            echo 'POSTGRES_DB=${{ secrets.POSTGRES_DB }}' >> /srv/cicdts/backend/.env
            echo 'POSTGRES_USER=${{ secrets.POSTGRES_USER }}' >> /srv/cicdts/backend/.env
            echo 'POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}' >> /srv/cicdts/backend/.env
            echo 'PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }}' >> /srv/cicdts/backend/.env
            echo 'PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }}' >> /srv/cicdts/backend/.env
          "

      - name: Do the deploy thing
        run: |
          ssh -o "StrictHostKeyChecking no" github@server "
            cd /srv/cicdts
            docker compose --env-file ./backend/.env up -d --build
          "
