name: Deploy to VPS via Tailscale

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connect Tailscal
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Do the deploy thing
        run: |
          ssh -o "StrictHostKeyChecking no" github@server "
            cd /srv/cicdts
            git pull
            docker compose up -d
          "
